App/urls.py
from django.urls import path, include
from .views import (
    HomePage, ProjectListPage, ProjectCreatePage, ProjectDetailPage,
    SignUp
)

app_name = 'App'
urlpatterns = [
    path('', HomePage, name='home'),
    path('projects/', ProjectListPage, name='projects'),
    path('add/project/', ProjectCreatePage, name='add-projects'),
    path('project/<int:pk>/', ProjectDetailPage, name='detail-projects'),

    path('signup/', SignUp.as_view(), name='signup'),
]

VoiceHunter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = []

urlpatterns += [ path('favicon.ico', RedirectView.as_view(url=settings.MEDIA_URL + 'main/favicon.png')) ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('App.urls')),
    path('', include('App.urls_api')),

]

templates/Base/Base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>:: VoiceHunter ::</title>
    <!-- Jquery CDN -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <!-- 부트스트랩 -->
    <link rel="stylesheet" type="text/css" href="{% static 'Base/css/bootstrap.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- 커스텀 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'Base/css/style.css' %}">
    <!-- 커스텀 JS -->
    <!--  <script src="{% static 'Base/js/jquery-ui.min.js' %}"></script> -->
    <!-- Noto Sans 폰트 -->
    <link href='https://cdn.rawgit.com/theeluwin/NotoSansKR-Hestia/master/stylesheets/NotoSansKR-Hestia.css' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
    <!-- 팝업 오픈소스 -->
    <!--<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>-->


</head>
<body>

<div id="content">
    {% include './Nav.html' %}
    {% block content %}
    {% endblock content %}
    {% include './Footer.html' %}
</div>
</body>
</html>

templates/Base/Footer.html
<div class="jumbotron w-100 mt-3 mb-0 p-4 footer">
	<div class="container">
		<p class="lead"><img src="/media/Main/logo.png"></p>
		<p>
			<br>
			ⓒ 2018 Tirrilee Inc.
		</p>
	</div>
</div>

templates/Base/Nav.html
{% load i18n %}
<nav class="navbar navbar-expand navbar-light bg-light p-1">
  <div class="container" style="padding: 0px 5px;">
    <a class="navbar-brand" href="{% url 'App:home' %}"><img src="/media/Main/logo.png" width="100"></a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav" style="width: 600px;">
        <a class="nav-item nav-link active" href="{% url 'App:add-projects' %}">{% trans 'register_project' %}</a>
        <a class="nav-item nav-link" href="{% url 'App:projects' %}">{% trans 'find_project' %}</a>
        <a class="nav-item nav-link ready">{% trans 'voice_actor_list' %}<small>(준비중)</small></a>
      </div>
      <div style="width: 254px;">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown float-right">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user }}님
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">
                <i class="fa fa-home"></i>
                마이페이지
              </a>
              <a class="dropdown-item" href="#">
                <i class="fa fa-cog" style="color: #8f9295; margin-right: 8px;"></i>
                계정 설정
              </a>
              <a class="dropdown-item" href="{% url 'logout' %}">
                <i class="fa fa-power-off" style="color: #8f9295; margin-right: 8px;"></i>
                로그아웃
              </a>
            </div>
          </li>
        {% else %}
          <a class="btn btn-light float-right" href="{% url 'App:signup' %}">회원가입</a>
          <a class="btn btn-light float-right" href="{% url 'login' %}">로그인</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>