App/urls.py
from django.urls import path, include
from .views import (
    HomePage, ProjectListPage, ProjectCreatePage, ProjectDetailPage,
    SignUp
)

app_name = 'App'
urlpatterns = [
    path('', HomePage, name='home'),
    path('projects/', ProjectListPage, name='projects'),
    path('add/project/', ProjectCreatePage, name='add-projects'),
    path('project/<int:pk>/', ProjectDetailPage, name='detail-projects'),

    path('signup/', SignUp.as_view(), name='signup'),
]

VoiceHunter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = []

urlpatterns += [ path('favicon.ico', RedirectView.as_view(url=settings.MEDIA_URL + 'main/favicon.png')) ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('App.urls')),
    path('', include('App.urls_api')),

]

App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# ------------------------------------------------------------------
# TableName   : Sido
# Description : 시/도 테이블
# ------------------------------------------------------------------
class Sido(models.Model):
    class Meta:
        verbose_name_plural = " 시/도 테이블"

    sido = models.CharField(max_length=10, verbose_name='시/도')

    def __str__(self):
        return str(self.sido)
# ------------------------------------------------------------------
# TableName   : Gugun
# Description : 구/군 테이블
# ------------------------------------------------------------------
class Gugun(models.Model):
    class Meta:
        verbose_name_plural = " 구/군 테이블"

    sido = models.ForeignKey(Sido, on_delete=models.CASCADE, verbose_name='시/도')
    gugun = models.CharField(max_length=10, verbose_name='구/군')

    def __str__(self):
        return str(self.gugun)

# ------------------------------------------------------------------
# TableName   : Project
# Description : 프로젝트 테이블
# ------------------------------------------------------------------
class Project(models.Model):
    class Meta:
        verbose_name_plural = "   프로젝트 테이블"
        ordering = ["-id"]
    TYPE_CHOICES = (
        ('both', '상관없음'),
        ('pro', '프로'),
        ('under', '언더'),

    )
    GENDER_CHOICES = (
        ('both', '성별무관'),
        ('male', '남자'),
        ('female', '여자'),

    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='유저')
    title = models.CharField(max_length=100, verbose_name='프로젝트 명')
    gugun = models.ForeignKey(Gugun, on_delete=models.CASCADE, verbose_name='위치')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, verbose_name='성우타입')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, verbose_name='성별')
    cost = models.PositiveIntegerField(verbose_name='예상금액')
    period = models.PositiveIntegerField(verbose_name='예상기간')
    deadline = models.DateField(verbose_name='마감날짜')
    content = models.TextField(verbose_name='프로젝트 내용')
    start_at = models.DateField(verbose_name='예상 시작날짜')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='등록일자')

    def __str__(self):
        return str(self.title)

# ------------------------------------------------------------------
# TableName   : Tag
# Description : 태그 테이블
# ------------------------------------------------------------------
class Tag(models.Model):
    class Meta:
        verbose_name_plural = "  태그 테이블"

    name = models.CharField(max_length=20, verbose_name='태그명')

    def __str__(self):
        return str(self.name)

# ------------------------------------------------------------------
# TableName   : ProjectTag
# Description : 프로젝트별 태그 테이블
# ------------------------------------------------------------------
class ProjectTag(models.Model):
    class Meta:
        verbose_name_plural = "  프로젝트별 태그 테이블"
        unique_together = ("project", "tag")

    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='프로젝트')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, verbose_name='태그')

    def __str__(self):
        return str(self.project)+' - '+str(self.tag)


# ------------------------------------------------------------------
# TableName   : ProjectApply
# Description : 프로젝트 지원 테이블
# ------------------------------------------------------------------
class ProjectApply(models.Model):
    class Meta:
        verbose_name_plural = "   프로젝트 지원 테이블"

    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='프로젝트')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='유저')
    cost = models.PositiveIntegerField(verbose_name='지원금액')
    period = models.PositiveIntegerField(verbose_name='지원기간')
    content = models.TextField(verbose_name='지원내용')
    voice = models.FileField(verbose_name='녹음파일')

    def __str__(self):
        return str(self.project)+' - '+str(self.user)

templates/ProjectList/Pagenation.html
<ul class="pagination float-right mt-2">
  {% if items.has_previous %}
    <li class="page-item">
  		<a class="page-link" href="?page=1">&laquo;</a>
    </li>
    <li class="page-item">
    	<a class="page-link" href="?page={{ items.previous_page_number }}">{{ items.previous_page_number }}</a>
    </li>
  {% else %}
    <li class="page-item disabled">
  		<a class="page-link" href="?page=1">&laquo;</a>
    </li>
  {% endif %}
    <li class="page-item active">
  		<span class="page-link">{{ items.number }}</span>
    </li>

  {% if items.has_next %}
  	<li class="page-item">
  		<a class="page-link" href="?page={{ items.next_page_number }}">{{ items.next_page_number }}</a>
    </li>
  	<li class="page-item">
  		<a class="page-link" href="?page={{ items.next_page_number }}">&raquo;</a>
    </li>
  {% else %}
    <li class="page-item disabled">
  		<a class="page-link">&raquo;</a>
    </li>
	{% endif %}
</ul>

templates/ProjectList/ProjectList.html
{% load humanize %}
<div class="row mt-0">
	{% for item in items %}
	<div class="col-12">
		<div class="card item bg-light mb-1">
		  <div class="card-body">
		    <h6 class="card-title text-primary">
		    	<a href="{% url 'App:detail-projects' pk=item.project.id %}">[{{ item.project.get_gender_display }}] {{ item.project.title }}</a>
			</h6>
		    <h5 class="project-element-list">
		    	<span class="project-element-money" style="padding-right: 7px;">
		    		<i class="fa fa-krw mr-1"></i> 
		    		<strong>예상금액 {{ item.project.cost|intcomma }}원</strong>
		    	</span> 
		    	<span class="project-element-day project-border" style="padding-left: 7px; padding-right: 7px;">
		    		<i class="fa fa-clock-o mr-1"></i>
		    		<strong>예상기간 {{ item.project.period }}일</strong>
		    	</span>
		    	<span class="project-element-proposal" style="padding-left: 7px;">
		    		등록일자 {{ item.project.created_at|date:"Y년 m월 d일" }}
		    	</span>
		    </h5>
		    <div class="project-unit-desc">
		    	<p class="card-text" style="width: 629px;color: #999;">{{ item.project.content }}</p>
		    	<div class="outer-info">
		    		<div class="outer-info-upper-data">
		    			<i class="fa fa-clock-o mr-1"></i>
		    			<span>마감 <strong>{{ item.project.deadline|timeuntil}} 전</strong></span>
		    		</div>
		    		<div class="outer-info-under-data">
		    			<i class="fa fa-pencil mr-1"></i>
		    			<span class="">지원자 <strong>{{ item.apply }}명</strong></span>
		    		</div>
		    	</div>
		    	<div style="clear: both;"></div>
		    </div>
		    <p class="project-skills-tag-viewbox">
		    	{% for tag in item.tags %}
		    		<span class="skills-tag">{{tag.tag}}</span>
		    	{% endfor %}
		    	...
		    </p>
		  </div>
		</div>
	</div>
	{% endfor %}
</div>

templates/ProjectList/ProjectListPage.html
{% extends "Base/Base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'ProjectList/css/style.css' %}">

<div class="container mb-5">
	{% include './Search.html' %}
	{% include './ProjectList.html' %}
	{% include './Pagenation.html' %}
</div>
</div>


{% endblock%}

templates/ProjectList/Search.html
{% load humanize %}
<div class="row mt-3">
	<div class="col-12">
		<div class="card bg-light mb-1 search-card">
            <div class="card-body">
            	<div style="width: 60%;float: left;">
            		<h5 class="card-title">프로젝트 찾기</h5>
              		<p class="card-text">{{ projects_len|intcomma }}개의 프로젝트에 지원가능합니다.</p>
            	</div>
				<form class="mt-5" method="get" action="" style="float: right;">
					<input id='search-input' type="text" name="q" value="{{search}}">
					<input type="number" name="page" value="{{ page }}" hidden="">
					<button class="search-btn btn-primary" type="submit">검색</button>
				</form>
            </div>
         </div>
	</div>
</div>