App/urls.py
from django.urls import path, include
from .views import (
    HomePage, ProjectListPage, ProjectCreatePage, ProjectDetailPage,
    SignUp
)

app_name = 'App'
urlpatterns = [
    path('', HomePage, name='home'),
    path('projects/', ProjectListPage, name='projects'),
    path('add/project/', ProjectCreatePage, name='add-projects'),
    path('project/<int:pk>/', ProjectDetailPage, name='detail-projects'),

    path('signup/', SignUp.as_view(), name='signup'),
]

VoiceHunter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = []

urlpatterns += [ path('favicon.ico', RedirectView.as_view(url=settings.MEDIA_URL + 'main/favicon.png')) ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('App.urls')),
    path('', include('App.urls_api')),

]

App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# ------------------------------------------------------------------
# TableName   : Sido
# Description : 시/도 테이블
# ------------------------------------------------------------------
class Sido(models.Model):
    class Meta:
        verbose_name_plural = " 시/도 테이블"

    sido = models.CharField(max_length=10, verbose_name='시/도')

    def __str__(self):
        return str(self.sido)
# ------------------------------------------------------------------
# TableName   : Gugun
# Description : 구/군 테이블
# ------------------------------------------------------------------
class Gugun(models.Model):
    class Meta:
        verbose_name_plural = " 구/군 테이블"

    sido = models.ForeignKey(Sido, on_delete=models.CASCADE, verbose_name='시/도')
    gugun = models.CharField(max_length=10, verbose_name='구/군')

    def __str__(self):
        return str(self.gugun)

# ------------------------------------------------------------------
# TableName   : Project
# Description : 프로젝트 테이블
# ------------------------------------------------------------------
class Project(models.Model):
    class Meta:
        verbose_name_plural = "   프로젝트 테이블"
        ordering = ["-id"]
    TYPE_CHOICES = (
        ('both', '상관없음'),
        ('pro', '프로'),
        ('under', '언더'),

    )
    GENDER_CHOICES = (
        ('both', '성별무관'),
        ('male', '남자'),
        ('female', '여자'),

    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='유저')
    title = models.CharField(max_length=100, verbose_name='프로젝트 명')
    gugun = models.ForeignKey(Gugun, on_delete=models.CASCADE, verbose_name='위치')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, verbose_name='성우타입')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, verbose_name='성별')
    cost = models.PositiveIntegerField(verbose_name='예상금액')
    period = models.PositiveIntegerField(verbose_name='예상기간')
    deadline = models.DateField(verbose_name='마감날짜')
    content = models.TextField(verbose_name='프로젝트 내용')
    start_at = models.DateField(verbose_name='예상 시작날짜')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='등록일자')

    def __str__(self):
        return str(self.title)

# ------------------------------------------------------------------
# TableName   : Tag
# Description : 태그 테이블
# ------------------------------------------------------------------
class Tag(models.Model):
    class Meta:
        verbose_name_plural = "  태그 테이블"

    name = models.CharField(max_length=20, verbose_name='태그명')

    def __str__(self):
        return str(self.name)

# ------------------------------------------------------------------
# TableName   : ProjectTag
# Description : 프로젝트별 태그 테이블
# ------------------------------------------------------------------
class ProjectTag(models.Model):
    class Meta:
        verbose_name_plural = "  프로젝트별 태그 테이블"
        unique_together = ("project", "tag")

    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='프로젝트')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, verbose_name='태그')

    def __str__(self):
        return str(self.project)+' - '+str(self.tag)


# ------------------------------------------------------------------
# TableName   : ProjectApply
# Description : 프로젝트 지원 테이블
# ------------------------------------------------------------------
class ProjectApply(models.Model):
    class Meta:
        verbose_name_plural = "   프로젝트 지원 테이블"

    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='프로젝트')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='유저')
    cost = models.PositiveIntegerField(verbose_name='지원금액')
    period = models.PositiveIntegerField(verbose_name='지원기간')
    content = models.TextField(verbose_name='지원내용')
    voice = models.FileField(verbose_name='녹음파일')

    def __str__(self):
        return str(self.project)+' - '+str(self.user)

templates/ProjectCreate/CreateForm.html
{% load static %}
<div class="row mt-1">
	<div class="col-12">
    <form method="POST">
      {% csrf_token %}
		  <div class="card bg-light mb-2 search-card">
        <div class="card-body m-auto">
          <table>
            {{ form.as_table }}
          </table>
          <button id="Validate" class="btn btn-primary w-100 mt-5" type="button" data-toggle="modal" data-target="">프로젝트 등록하기</button>
        </div>
      </div>
    </form>
	</div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="{% static 'Base/js/jquery-ui.js' %}"></script>
<link rel="stylesheet" href="{% static 'Base/css/jquery-ui.min.css' %}">
<link rel="stylesheet" href="{% static 'Base/css/jquery-ui.theme.min.css' %}">
<script>
  
  // 3자리마다 콤마
  // $('input[name=cost]').keyup(function(){
  //   var replace_val = this.value.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
  //   $('input[name=cost]').value(replace_val);
  // })
  $( document ).ready(function() {
    $('textarea[name=content]').text('\n< 프로젝트 내용 >\n\n\n\n< 샘플 대본 >')
  });

  $( "#period_datepicker" ).datepicker({
    dateFormat: "yy-mm-dd",
    beforeShow: function(){    
      $('#ui-datepicker-div').removeClass('deadline_datepicker');
      $('#ui-datepicker-div').removeClass('start_datepicker');
      $('#ui-datepicker-div').addClass(this.id);
    }
  });
  $( "#deadline_datepicker" ).datepicker({
    dateFormat: "yy-mm-dd",
    beforeShow: function(){    
      $('#ui-datepicker-div').removeClass('period_datepicker');
      $('#ui-datepicker-div').removeClass('start_datepicker');
      $('#ui-datepicker-div').addClass(this.id);
    }
  });
  $( "#start_datepicker" ).datepicker({
    dateFormat: "yy-mm-dd",
    beforeShow: function(){    
      $('#ui-datepicker-div').removeClass('period_datepicker');
      $('#ui-datepicker-div').removeClass('deadline_datepicker');
      $('#ui-datepicker-div').addClass(this.id);
    }
  });

  $('#Validate').click(function(){
    var title = $("#id_title").val()
    var gugun = $("#id_gugun").val()
    var type = $("#id_type").val()
    var gender = $("#id_gender").val()
    var cost = $("#id_cost").val()
    var period = $("#id_period").val()
    var deadline = $("#deadline_datepicker").val()
    var content = $("#id_content").val()
    var start_at = $("#start_datepicker").val()

    if (title=="" || cost=="" || period=="" || deadline=="" || start_at==""){
      $('#Validate').attr('data-target', '#Error')
    }
    else{
      $('#Validate').attr('data-target', '#Submit')
    }
  })
</script>

templates/ProjectCreate/ProjectCreatePage.html
{% extends "Base/Base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'ProjectCreate/css/style.css' %}">

{% include './modalSubmit.html' %}
{% include './modalError.html' %}
<div class="container">

	{% include './Title.html' %}

	{% include './CreateForm.html' %}
</div>
{% endblock%}

templates/ProjectCreate/Title.html
<div class="row mt-3">
	<div class="col-12">
		<div class="card bg-light mb-2 search-card">
            <div class="card-body">
            	<div style="width: 60%;float: left;">
            		<h5 class="card-title">프로젝트 등록</h5>
              		<p class="card-text">프로젝트에 알맞는 성우를 찾아보세요</p>
            	</div>
            </div>
         </div>
	</div>
</div>

templates/ProjectCreate/modalError.html
<!-- Modal -->
<div class="modal fade" id="Error" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">알림</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        빈칸을 전부 채워주세요
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">확인</button>
      </div>
    </div>
  </div>
</div>

templates/ProjectCreate/modalSubmit.html
<!-- Modal -->
<div class="modal fade" id="Submit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">태그 추가</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <select id="id_tag" class="form-control form-control-sm mb-3">
          {% for tag in tags %}
            <option value="{{ tag.id }}">{{ tag.name }} 목소리</option>
          {% endfor %}
        </select>
        <div id="tag_badge">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
        <button id="submit" type="button" class="btn btn-primary">등록</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('#id_tag').change(function() {
    

    var tag_badge = "<span pk='"+this.value+"' class='badge badge-pill badge-primary m-1' "
    tag_badge    += "onclick='" + '$(".badge[pk='+this.value+']"'+").remove()'>"
    tag_badge    += $('#id_tag option[value='+this.value+']').text() + " X</span>"

    if ($('.badge[pk='+this.value+']').length==0){
      $( "#tag_badge" ).append(tag_badge);
    }
  })

  $('#submit').click(function(){
    var tag_list = $("#tag_badge span")
    var tag_pk_list = []
    for (i=0; i<tag_list.length; i++){
      tag_pk_list.push(tag_list[i].attributes.pk.value)
    }
    var title = $("#id_title").val()
    var gugun = $("#id_gugun").val()
    var type = $("#id_type").val()
    var gender = $("#id_gender").val()
    var cost = $("#id_cost").val()
    var period = $("#id_period").val()
    var deadline = $("#deadline_datepicker").val()
    var content = $("#id_content").val()
    var start_at = $("#start_datepicker").val()

    console.log('title : ', title)
    console.log('gugun : ', gugun)
    console.log('type : ', type)
    console.log('gender : ', gender)
    console.log('cost : ', cost)
    console.log('period : ', period)
    console.log('deadline_datepicker : ', deadline)
    console.log('content : ', content)
    console.log('start_datepicker : ', start_at)

    console.log(tag_pk_list)
    $.ajax({ 
        type: "POST", 
        url: "{% url 'API:api-add-project' %}",
        data: {
            'title': title,
            'gugun': gugun,
            'type':type,
            'gender':gender,
            'cost':cost,
            'period':period,
            'deadline':deadline,
            'content':content,
            'start_at':start_at,
            'tags':tag_pk_list.toString(),
            'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        dataType: "json", 
        success: function(response){
            console.log(response)
            if (response.message == 'success'){
              location.href = "/ko/project/"+response.pk
            }
            else{
              alert('다시 입력해주세요.')
              location.href = "/ko/add/project"
            }
        },
        error: function(request, status, error){
            alert("알수 없는 에러가 발생했습니다.")
        },
    });
  })
</script>